//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoTurno
    {
        public int Id_EmpleadoTurno { get; set; }
        public int EmpleadoId_empleado { get; set; }
        public int TurnoId_turno { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
